# Generated by Django 5.1.1 on 2024-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('tipo_motor', models.CharField(max_length=100)),
                ('sae', models.CharField(max_length=20)),
                ('tipo_filtro', models.CharField(max_length=100)),
                ('imagen_url', models.URLField(max_length=500)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('tipo_envase', models.CharField(max_length=100)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
